/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androndk_ndkhelloworld_JNILib */

#ifndef _Included_com_androndk_ndkhelloworld_JNILib
#define _Included_com_androndk_ndkhelloworld_JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androndk_ndkhelloworld_JNILib
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androndk_ndkhelloworld_JNILib_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_androndk_ndkhelloworld_JNILib
 * Method:    writeToFileInCNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androndk_ndkhelloworld_JNILib_writeToFileInCNDK
  (JNIEnv *, jobject);

/*
 * Class:     com_androndk_ndkhelloworld_JNILib
 * Method:    readFromFileInCNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androndk_ndkhelloworld_JNILib_readFromFileInCNDK
  (JNIEnv *, jobject);

/*
 * Class:     com_androndk_ndkhelloworld_JNILib
 * Method:    createFileInCNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androndk_ndkhelloworld_JNILib_createFileInCNDK
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
